### PR TITLE
Figures and tables

### PR DESCRIPTION
**Pull request by siddhss5**

### CODE REVIEW

**Comment by mklingen** [comment]
lgtm, but since one of the reviewers complained about the use of the term "Chisel" being vague, I'm not sure about keeping it in the title. "Chisel" also refers to the proprietary Google product we made while working there.

**Comment by idryanov** [comment]
+1 for removing Chisel as name

I'm not worried about google (I don't think they are going with that name),
but I agree about being vague.

On Wed, Jan 21, 2015 at 5:36 PM, mklingen <notifications@github.com> wrote:

> lgtm, but since one of the reviewers complained about the use of the term
> "Chisel" being vague, I'm not sure about keeping it in the title. "Chisel"
> also refers to the proprietary Google product we made while working there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mklingen/chiselpaper/pull/6#issuecomment-70936223>.
>



-- 
Ivan Dryanovski
The Graduate Center, City University of New York (CUNY)
CCNY Robotics Lab
http://robotics.ccny.cuny.edu/Dryanovski

**Comment by mklingen** [comment]
I merged it in and kept the additional figure Sidd made at the beginning, as well as our old figure (so they are duplicated). Will have to move around/merge some figures later to stay within the page limits.

**Comment by siddhss5** [comment]
1. I like that figure in the first page. It's captivating.
2. I LOVE the name CHISEL. We should totally stick to it. It'd be nice to
give a small one-sentence of why we named it but it's a really awesome name.
Sidd.

**Comment by mklingen** [comment]
Okay. Then I will add the following to the "space carving" section:

> By "Chiseling" away voxels that have been corrupted by noise, <blah blah blah>

**Comment by siddhss5** [comment]
Btw I added a handy `\chisel` LaTeX macro. It'd be great if we could populate that throughout the document. Right now `Chisel` doesn't stand out, so it's not clear it's the name of our algorithm and not the word.

**Comment by mklingen** [comment]
Sidd, I have started using your macro to describe the process of space carving. Another unrelated note: I changed all of the terms involving the word "Integration" to use the word "Fusion" instead, like most of the prior work does.

**Pull request merged**
